name: Sync to Gitee
on:
  push:
    branches: [main]

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Get current repo name(HTTPS)
        uses: actions/checkout@v4
        with:
              ref: main
              fetch-depth: 0
      - name: Check TOKEN_GITEE
        env:
          TOKEN_GITEE: ${{ secrets.TOKEN_GITEE }}
        run: |
          if [ -z "$TOKEN_GITEE" ]; then
            echo "Error: TOKEN_GITEE is empty!"
            exit 1
          fi
            echo "TOKEN_GITEE is set correctly."
            
      - name: Get REPO_NAME
        run: | 
          echo "REPO_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2)" >> $GITHUB_ENV
          REPO_OWNER=${{ github.repository_owner }} 
          echo "REPO_OWNER=${REPO_OWNER,,}" >> $GITHUB_ENV
          
      - name: Set up Gitee
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
        
      - name: Mirror to Gitee        
        run: |           
            git remote add gitee https://JenkinsRsWlan5:${{ secrets.TOKEN_GITEE }}@gitee.com/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}.git 
            echo "${{ env.REPO_OWNER }}"
            git push gitee HEAD:refs/heads/main --force